jserror: simplify custom error creation
The old API was needlessly complex and suggested that it could only be
used for DOMException (which is not the case).

(Also optimized out code lookup from the DOMException constructor.)